### ISSUE TITLE
Upstream CI doesn't run nightly

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-viz#101]
The upstream-examples-ci.yml doesn't run nightly. We need to add a `cron` directive to make sure it runs nightly at midnight. See what is done in geocat-comp's upstream-dev-ci.yml file https://github.com/NCAR/geocat-comp/blob/main/.github/workflows/upstream-dev-ci.yml

**Comment by pilotchute** [comment]
Should have been addressed in #99

**Comment by pilotchute** [comment]
marking as resolved.
