### ISSUE TITLE
Matplotlib is still pinned several major versions back

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-viz#104]
While addressing another issue, I noticed that viz still has matplotlib pinned to [version 3.5.3](https://matplotlib.org/stable/users/release_notes.html#version-3-5) and before. This may cause headaches for users trying to use geocat-viz with other packages since the latest Matplotlib version is 3.7.0. We should resolve [the issue that originally led us to pin](https://github.com/NCAR/geocat-viz/pull/90) this package version and un-pin Matplotlib

**Comment by jukent** [comment]
Places that pin matploblig:

https://github.com/NCAR/geocat-viz/blob/main/ci/docs.yml
https://github.com/NCAR/geocat-viz/blob/main/ci/environment.yml
https://github.com/NCAR/geocat-viz/blob/main/ci/upstream_environment.yml

**Comment by kafitzgerald** [comment]
I can't tell from the linked PR #90 why the matplotlib version was pinned.  I assume it was the issue with colormaps since things seem to be working with a newer version of matplotlib (including the skewt stuff) as long as I don't re-register the colormaps.  Might check in with someone on this though.

**Comment by jukent** [comment]
Great thanks Kaitlyn. That seems like a good sign. We can focus on the color map stuff.

**Comment by kafitzgerald** [comment]
As I mentioned on issue #112, I think we should be able to remove this pin now without having to implement our own cmap module for the time being.  

I'll put in a PR shortly.
