### ISSUE TITLE
ImportError: cannot import name 'cmaps' from 'geocat.viz' (/home/praveen/anaconda3/envs/geocat/lib/python3.11/site-packages/geocat/viz/__init__.py)

### ISSUE THREAD

**Issue by pravee3** [NCAR/geocat-viz#105]
Hi,

I am getting this error whenever I am trying to import the cmaps. Any help would be highly appreciated.

Thanks

**Comment by jukent** [comment]
Hi @pravee3 I'm looking into this now. Can you share your environment file and code snippet?

**Comment by kafitzgerald** [comment]
It looks like you might be trying to import `cmaps` from `geocat.viz`.  [cmaps](https://github.com/hhuangwx/cmaps) is a separate package so you should just be able to do `import cmaps`.  You can see a script using both geocat-viz and cmaps here: https://geocat-examples.readthedocs.io/en/latest/gallery/Contours/NCL_color_1.html

**Comment by kafitzgerald** [comment]
Some additional context: 
It looks like it was a [dependency at one point](https://github.com/NCAR/geocat-viz/commit/100e82623a55ceeee2e666bc54925bc228364206) and has since been removed.  

Hopefully the above comment helps you out.  Let us know if you're still running into trouble.

**Comment by pravee3** [comment]
Thanks @jukent and @kafitzgerald. I also think the problem was the dependency of cmaps with geocat-viz because I was able to import it earlier but not anymore. I am importing cmaps separately and using the colormaps. Thanks again.

Praveen

**Comment by jukent** [comment]
I'll close this issue as it seems you have it working on your end now. Please don't hesitate to reach out again if you need anything.
