### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-viz#120]
Needs to incorporate some changes to feedstock (https://github.com/conda-forge/geocat-viz-feedstock/pull/7) @pilotchute @anissa111 

## For Package Leader

Version: v2023.05.0
Plain text summary of significant changes:

Added new functionality for pressure-height plots, documentation and packaging overhauls.

## Release progress checklist

- [ ] CI tests are passing
- [ ] release-notes.rst has been updated with latest release notes
- [ ] a new tag and release has been made on GitHub
- [ ] feedstock PR has been merged
- [ ] release on pypi action has been triggered on the tag
- [ ] new version can be installed via pip
- [ ] new version can be installed via conda

**Comment by jukent** [comment]
I'd like to merge these PRs first https://github.com/NCAR/geocat-viz/pull/122 and #123

**Comment by jukent** [comment]
Merged! Thanks @pilotchute !

**Comment by anissa111** [comment]
Closing as completed as v2023.05.0 is live on pypi and conda-forge
