### ISSUE TITLE
Possible Testing Schemes

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-viz#126]
Viz doesn't have many tests because the products are visually as expected or not, but how does matplotlib or cartopy have a testing scheme?

**Comment by jukent** [comment]
I think the first testing scheme we want to include is independent viz examples that build. First, let's take inventory of how many tests we need to add at minimum.

In util.py there are 16 different methods. In taylor.py there are 11. I'll start with util.

**Comment by jukent** [comment]
Add example script to each function (divvy these up?):

- [ ] add_height_from_pressure_axis() - JK
- [ ] add_lat_lon_gridlines() - JK
- [ ] add_lat_lon_ticklabels() - JK
- [ ] geocat.viz.taylor.TaylorDiagram()
- [ ] set_tick_direction_spine_visibility() - JK
- [ ] add_right_hand_axis() - JK
- [ ] add_major_minor_ticks() - JK
- [ ] set_titles_and_labels()
- [ ] set_axes_limits_and_ticks()
- [ ] truncate_colormap() - KF
- [ ] xr_add_cyclic_longitudes() - KF
- [ ] set_map_boundary() - KF
- [ ] find_local_extrema()
- [ ] plot_contour_labels()
- [ ] plot_extrema_labels()
- [ ] set_vector_density()
- [ ] get_skewt_vars()

Steps:

1. Search geocat-examples for simple example of fx, par down even more
2. Make .ipynb file for example
3. Save thumbnail
4. Add to docs/gallery.yml
5. Add link to fx docstring under examples (before examples gallery examples) EX: ‘See this example notebook: :doc:`../../examples/add_height_from_pressure_axis`.     More in-depth plotting examples that utilize this function are in the GeoCAT-Examples Gallery.’
7. Add to examples.rst

**Comment by jukent** [comment]
Talked to @dcamron from Metpy about what they do. He directed me to their pizel-by-pixel testing using [pytest-mpl](https://pypi.org/project/pytest-mpl/), but indicated that they were unhappy with this scheme and didn't want us to get tangled up in it as they are investigating a better solution themselves. Still posting links here for now and will try to set up a meeting to learn about what it is they do not like about these tests.

https://github.com/Unidata/MetPy/blob/main/tests/plots/test_skewt.py
https://github.com/Unidata/MetPy/tree/main/tests/plots/baseline

**Comment by kafitzgerald** [comment]
Maybe this belongs in a different issue, but I just noticed we're not actually building the docs in the nightly CI (which just failed, but because of a connectivity fluke).  It would be nice to have some sort of tests run there.

We might also want to think about something a little more robust since a few things just got caught over on geocat-examples that probably should be failing over here as well (i.e. the matplotlib 3.8 API change and the problem with sphinx-book-theme and sphinx 7).

**Comment by jukent** [comment]
@kafitzgerald What is the status of  truncate_colormap(), xr_add_cyclic_longitudes(), and set_map_boundary() examples?

**Comment by kafitzgerald** [comment]
All four w/ my initials are in progress.  I got a bit hung up on how best to display the colormaps, but can get back to those this week and get them in.

**Comment by jukent** [comment]
I'll work on the skewT one this week.
