### ISSUE TITLE
AttributeError: module 'geocat.viz' has no attribute 'TaylorDiagram'

### ISSUE THREAD

**Issue by pravee3** [NCAR/geocat-viz#136]
Hi,

I was trying to use the Taylor diagram code from geocat-viz. But I am getting this attribute error when trying to plot it. I have installed geocat-viz in my geocat environment and the error seems to persist even after updating the geocat-viz.

Any help would be highly appreciated.

Thanks
Praveen

**Comment by kafitzgerald** [comment]
Hi Praveen,

Thanks for reporting this.  

Could you share what version(s) you're using and provide a short code snippet?

**Comment by pravee3** [comment]
Hey,

Thanks for the quick reply. I guess below is the version of geocat-viz:
geocat-viz-2022.07.0-py_0/

And I am basically using the NCL_taylor_8.py script.

![image](https://github.com/NCAR/geocat-viz/assets/130973563/bfd5972c-ab1c-4b3d-acc1-2d4e2e6a6dd7)

Thanks

**Comment by kafitzgerald** [comment]
It looks like something is going wrong with your environment and/or install.  

You do have an older version of geocat-viz (the latest is now 2023.07.0), but the NCL_taylor_8.py example should still work.  

I'd suggest trying to reinstall geocat-viz in a new/clean environment if possible.  

You might also try the [newest version from conda-forge](https://anaconda.org/conda-forge/geocat-viz) using `conda install -c conda-forge geocat-viz`.

**Comment by pravee3** [comment]
Hi,

Thank you for the suggestion. I have re-installed the anaconda and then installed the geocat-viz and it is working fine now.

Many Thanks
Praveen

**Comment by kafitzgerald** [comment]
Glad you were able to get things working!
