### ISSUE TITLE
New Viz Release

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-viz#138]
## For Package Leader

Version: v2023.7.0

Matplotlib has been unpinned and an examples gallery added.

## Release progress checklist

- [x] CI tests are passing
- [x] release-notes.rst has been updated with latest release notes
- [x] a new tag and release has been made on GitHub
- [x] feedstock PR has been merged
- [x] release on pypi action has been triggered on the tag
- [x] new version can be installed via pip
- [x] new version can be installed via conda

**Comment by anissa111** [comment]
Done and verified!
