### ISSUE TITLE
Flip y-axis for the add_height_from_pressure_axis usage example

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/geocat-viz#151]
While looking into #150, I noticed the pressure axis (y) goes from low (bottom) to high (top) in the following usage example: https://geocat-viz.readthedocs.io/en/latest/examples/add_height_from_pressure_axis.html

Typically this is reversed.  

I'm guessing the code to do that was stripped out in the interest of keeping this example short, but we might think about adding that back in so it's more aligned with what folks are used to seeing.

**Comment by jukent** [comment]
Yes this is concerning and worth working on. Thanks for noticing this.
