### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by kafitzgerald** [NCAR/geocat-viz#154]
Just realized I missed the release notes in my latest PR (and potentially related items).  

I might pull together a quick PR template to help with this.  I think GeoCAT-comp has one we could cut down to the relevant items.

**Comment by erogluorhan** [comment]
@kafitzgerald FYI: No reviewer listed in #157

**Comment by kafitzgerald** [comment]
Thanks!  I didn't want to poke @jukent yesterday, but wanted her to see this.   Probably wasn't necessary, but figured this wasn't urgent either.
