### ISSUE TITLE
Update assets to comply with the New NSF Branding Theme

### ISSUE THREAD

**Issue by erogluorhan** [NCAR/geocat-viz#187]
Update documentation site, pages, etc. to reflect the NSF branding policy changes (e.g. NSF NCAR) whereever applicable, e.g. logos,  text, etc.

**Comment by kafitzgerald** [comment]
Oddly enough it looks like we don't have any text that needs to be updated.  

I presume the current logo in the documentation is the best we have right now or is there something new?

**Comment by erogluorhan** [comment]
Actually, @kafitzgerald, I just noticed a small issue with the logo; "NCAR" is not visible with the light version of it, the dark version could be better:

<img width="531" alt="image" src="https://github.com/NCAR/geocat-viz/assets/32553057/e04c1a5b-0dae-40c6-aa4f-a5ab13e1a119">
