### ISSUE TITLE
Quantifying completeness of NCL visualization examples and functionality in Python

### ISSUE THREAD

**Issue by jukent** [NCAR/geocat-viz#227]

**Comment by jukent** [comment]
[NCL Completeness](https://docs.google.com/spreadsheets/d/1ZLoouhvsyYFtr9v-iwVHpt1WuJ3naGnupb4_gArLrvI/edit#gid=0)

**Comment by kafitzgerald** [comment]
I haven't finished going through the individual functions and might wait on doing that, but I did take a pass through all of the NCL Applications visualization category listings and NCL Visualization Gallery.  There's a number of GeoCAT-examples for each category and some notes about the status, potential needs, requests I'm aware of, etc.

Maybe we can chat about some high level takeaways at an upcoming meeting or team time.

I haven't logged issues for everything I found that's missing, but did try to link and clarify pre-existing issues as it made sense.
