### ISSUE TITLE
Add support to facilitate locating quivers on triangle meshes

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-viz#24]
When generating 2D hedgehog (quiver) plots users typically want to locate quiver glyphs on at 2D lattice. 
The MPL quiver function operates on a list of 2D vectors specified along with their coordinates. Thus for regular grids it is easy to locate quivers along a lattice simply by locating them at grid nodes. For unstructured data locating the quivers at grid nodes will not result in a regular placement of glyph locations. To support placing quivers at regular intervals the unstructured mesh needs to be sampled at arbitrary locations. This feature request is for a mechanism to sample an MPL triangle mesh such that at regularized list of vectors and their coordinates can be generated and fed into the MPL quiver function.

**Comment by kafitzgerald** [comment]
@erogluorhan should this go to UXarray?

**Comment by erogluorhan** [comment]
> @erogluorhan should this go to UXarray?

Yes; thanks for pointing out! Created UXarray [issue #593](https://github.com/UXARRAY/uxarray/issues/593), can close here
