### ISSUE TITLE
Streamlines for triangle meshes

### ISSUE THREAD

**Issue by clyne** [NCAR/geocat-viz#25]
Add support to integrate and display streamlines for data sampled on a triangle mesh. Currently the MPL streamline function only operates on structured grids.

**Comment by kafitzgerald** [comment]
Similarly, @erogluorhan should this go to UXarray?

**Comment by erogluorhan** [comment]
> Similarly, @erogluorhan should this go to UXarray?

Yes; thanks for pointing out! Created UXarray [issue #594](https://github.com/UXARRAY/uxarray/issues/594), can close here
