### ISSUE TITLE
Creating a shape file for landmasses without covering major lakes

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-viz#27]
Shape files currently available through [natural earth data](https://www.naturalearthdata.com/) draw land masses by specifying the boundary for the coastlines and then filling the whole area in. This covers up lakes which is problematic for some examples in the geocat examples gallery (https://github.com/NCAR/GeoCAT-examples/pull/189). We should make a shape file that doesn't cover major lakes or find a preexisting one.

**Comment by pilotchute** [comment]
Probably best done buy using unions of the land and water geometry:
```
land_shp_fname = shpreader.natural_earth(resolution='50m', category='physical', name='land')
land_geom = unary_union(list(shpreader.Reader(land_shp_fname).geometries()))
land = prep(land_geom)

lake_shp_fname = shpreader.natural_earth(resolution='50m', category='physical', name='lakes')
lake_geom = unary_union(list(shpreader.Reader(lake_shp_fname).geometries()))
lake = prep(lake_geom)


def watermask(data,lon_a, lat_a, land, lake):
    res = data.copy()
    lon_a = lon_a
    for lat in range(data.shape[0]):
        for lon in range(data.shape[1]):
            if land.contains(sgeom.Point(lon_a[lat,lon], lat_a[lat,lon])) and not lake.contains(sgeom.Point(lon_a[lat,lon], lat_a[lat,lon])):
                res[lat,lon] = np.nan
    return res
sphere_noise_water = watermask(sphere_noise_xr,lon2d,lat2d,land,lake)
```

**Comment by pilotchute** [comment]
I'm not sure if a shapefile can have and outer and inner edge, I think the underlying structure may only have the outer bound. Not sure of a ring can be made as a shape, as I think I've not seen one.

**Comment by jukent** [comment]
Linked PR demonstrates how to do this in geocat_examples. No new functionality is added to viz.
