### ISSUE TITLE
Addressing single character color deprecation

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-viz#29]
`matplotlib` will no longer be supporting using single character color names (i.e. `'r'` instead of `'red'`). This change will take effect in two minor releases from now as stated [here](https://matplotlib.org/3.2.1/api/api_changes.html#colors). This means that we will need to go through all of `geocat-viz` and make sure that we switch from `'r'` to `'red'`, `'k'` to `'black'`, `'b'` to `'blue'`, etc.

This relates to a similar issue in `geocat-examples` https://github.com/NCAR/GeoCAT-examples/issues/265

**Comment by dcherian** [comment]
hmmm... I don't think that is right.

> Using a string of single-character colors as a color sequence (e.g. "rgb") is deprecated. Use an explicit list instead.

I think this means that we can't use a string of multiple single-character colors.

**Comment by hCraker** [comment]
Ah you may be right. Let me see if I can find where I first encountered this deprecation warning for reference.

**Comment by hCraker** [comment]
I remember encountering the warning when running some of the examples in the geocat-examples repo, but I can't seem to find the file that produced it. I just ran the current version of every example file locally, and I didn't encounter the warning. The whole reason why I opened this issue and the related one in geocat-examples if because I got this warning, so now I'm not sure what changed.
