### ISSUE TITLE
Reduce density for vector plots

### ISSUE THREAD

**Issue by mnlevy1981** [NCAR/geocat-viz#3]
A python function that reduces the density of vectors (similar to `vcMinDistanceF` property in NCL) would be nice. Maybe it would return a dataset with the same dimensions as the original, but with `nan`s in places where we don't want to draw arrows in `plt.quiver()`?

**Comment by dcherian** [comment]
wouldn't `ds.isel(lat=slice(None,None,4), lon=slice(None,None,4))` do what you want?

**Comment by mnlevy1981** [comment]
I think a function that returns `ds.isel(lat=slice(None,None,lat_every), lon=slice(None,None,lon_every))` for some parameters `lat_every` and `lon_every` is what we want, but knowing how to determine those parameters (especially relative to a `vcMinDistanceF` specified in an NCL script) is non-trivial.
