### ISSUE TITLE
Which GeoCAT tutorial to start with?

### ISSUE THREAD

**Issue by eroesler** [NCAR/geocat-viz#39]
I'm a long-time NCL user but have been motivated (several times) to try python.   I usually land flat because of mixed functionality in environments and errors set by my institution's proxy in retrieving packages.  I tried again, though, with the  'Getting Started' documentation written by the NCAR graphics team under project Pythia. Pythia started slow, which was good, understanding the audience needing to make plots and do data analysis, but it ended before it every said exactly how to start making NCL-quality plots.  I've found Pangea, Metpy, and now Geocat.   There are three (or four?) different Geocat repositories, with Github and Read.io documentation.  Some say to clone the repo with git, some say have the conda package manager do it. All the documentation stops a bit short of a full 'Getting Started' guide like NCL used to have.  I assume after I create a new environment (which sometimes fails, sometimes not), and activate it (but not seeing that activation confirmation in the command line prompt) that everything is okay, and I can 'python script-example.py', but errors are thrown.     

Do I clone all three (or four), or just one?  Where to I post if I run into an error?  I started with the Examples, but I get an error saying xarray is not found.  Xarray is a very neccessary package, if I'm understanding python correctly.  I see the xarray downloaded and unzipped in the .condarc package directory, but can someone state if I should have it somewhere else?  Am I missing an environment variable?  Or is there another GeoCat repo I should download?  After this n-th try of trying python, I'm closing in on getting a Matlab subscription. :(  Thank you for your advice and help.  I appreciate your vision in trying to make a one-stop shop for environments and plots for earth scientists.

**Comment by erogluorhan** [comment]
Hi @eroesler ,

Thank you very much for sharing a lot of valuable details about your experience! Sorry for the delayed reply though! Your findings/thoughts are very helpful for us to understand user experience with our toolkits and documentation. Let me try my best to breakdown atomic issues pointed out in your initial message and provide one-by-one answers if possible:

>  I tried again, though, with the 'Getting Started' documentation written by the NCAR graphics team under project Pythia. Pythia started slow, which was good, understanding the audience needing to make plots and do data analysis, but it ended before it every said exactly how to start making NCL-quality plots.

Spinning up to the Python Ecosystem and getting used to utilizing Python packages and resources is a different experience than learning a toolkit that is dedicated to specific functionalities such as NCL/PyNGL. With that being said, "Pythia is a community educational resource for helping students, scientists, and educators learn how to analyze and visualize geosciences data using the Scientific Python Ecosystem." So, it would be great to start digging into [Project Pythia](https://projectpythia.org/index.html#) resources such as 
1. [Project Pythia Foundations Book](https://foundations.projectpythia.org/landing-page.html) to first obtain foundational skills  about Python-based geoscientific computing (e.g. why Python, Xarray, matplotlib, cartopy, etc)
2. [Pythia Resource Gallery](https://projectpythia.org/gallery.html) to reach documentation of several resources including GeoCAT etc.

However, please also keep in mind that Project Pythia has had its "soft" launch in June, and not all of the advanced topics/content are available yet.

I am cc'ing @clyne , Project Pythia PI, at this point to let him know your experience aabout Project Pythia.

My answers to your remaining points to be continued...

**Comment by erogluorhan** [comment]
Hi @eroesler , I wanted to follow up with you to see if you had another chance / cycle to give a try to Python or you are fine with Matlab :) 

If the former, then could you please let me know how your experience with Pythia resources was (if you have had a look into)? I am happy to assist further into GeoCAT stack.

**Comment by erogluorhan** [comment]
Closing this for now due to inactivity but I am happy to reopen and discuss anything needed
