### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by QiaomeiFeng** [NCAR/geocat-viz#51]
Hi, I have a problem.

Module 'geocat.viz.util' has no attribute 'set_axes_limits_and_ticks'.

I'd appreciate it if you could help me out。

**Comment by anissa111** [comment]
Hello @QiaomeiFeng, sorry for the slow response. I just wanted to let you know that I am currently looking in to this!

**Comment by anissa111** [comment]
@QiaomeiFeng, this is a duplicate issue to #49, I'm going to close this issue and encourage you to look at the other issue report for updates.

**Comment by QiaomeiFeng** [comment]
Thanks for your help!
