### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by DamienIrving** [NCAR/geocat-viz#65]
I installed geocat-viz on both my Mac and a Linux machine using the following command:
```
$ conda create -n geocat -c conda-forge -c ncar geocat-viz
```
When I try and import any of the libraries within geocat-viz (on the Mac or Linux machine) I get a `ModuleNotFoundError`. For example:
```python
from geocat.viz import util as gvutil
```
```error
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from geocat.viz import util as gvutil

File ~/miniconda3/envs/geocat/lib/python3.10/site-packages/geocat/viz/__init__.py:1, in <module>
----> 1 from .contourf import *
      2 from .plot_util import *
      3 from .taylor import *

File ~/miniconda3/envs/geocat/lib/python3.10/site-packages/geocat/viz/contourf.py:6, in <module>
      3 import numpy as np
      4 import cartopy.crs as ccrs
----> 6 from src.geocat.viz.plot_util import NCL_Plot
      9 class Contour(NCL_Plot):
     10     """Create contour plot.
     11 
     12     Args
   (...)
     51         A contour plot with specified input style.
     52     """

ModuleNotFoundError: No module named 'src'
```

**Comment by erogluorhan** [comment]
Hi @DamienIrving ,

Thanks for reaching out! GeoCAT-viz, in its latest version of v2022.04.0, has gone into significant changes. I am assigning our team members (@anissa111 and @michaelavs ) who led this effort, and they could give you the best instructions to overcome this issue.

Best,

**Comment by anissa111** [comment]
Hello @DamienIrving! As mentioned, the latest release has gone through significant changes. For the time being until a more thorough fix come through, I suggest using the last stable released version, `v2020.7.30.1`. That command would look like
```
conda create -n geocat -c conda-forge -c ncar geocat-viz=2020.7.30.1
```

I will come back and update this issue when we've fixed the actual issue!

**Comment by anissa111** [comment]
Hello @DamienIrving! We've made a release that fixes your issue. You should be able to use [v2022.05.0](https://github.com/NCAR/geocat-viz/releases/tag/v2022.05.0) and newer!

**Comment by DamienIrving** [comment]
Thanks so much, @anissa111 - I re-installed and it's working great :smile:
