### ISSUE TITLE
Known Contour Usage Issues

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-viz#70]
This is just a place to collect issues we find while using the new contourf functionality. Will be updated as needed

- [ ]  does not support passing in pre-created fig
- [ ] should make sure kwargs match up with matplotlib defaults
- [ ] improve "unused kwargs" warning

**Comment by doqhne** [comment]
Additional issues:
- [ ] cb_shrink kwarg does not work correctly
- [ ] Does not support major/minor tick mark length and width customization (can be done outside of Contour function)
- [ ] Does not support customizing number of minor tick marks per major. This can be done by using the geocat-viz add_major_minor_ticks() function after Contour, but this resets tick label size formatting.
- [ ] Does not support removing degree symbol from lat/lon tick labels. (This can be done outside of Contour function)
- [ ] Colorbar ticks can't be removed

**Comment by kafitzgerald** [comment]
Seems like this actually refers to functionality being developed for GeoCAT-viz that was moved to an experimental branch.  

@anissa111 is it worth keeping this open?  

If there's more to this, maybe you can fill me in during a co-working time soon.

**Comment by anissa111** [comment]
@kafitzgerald Yeah, this is likely good to close as not planned
