### ISSUE TITLE
Fix right hand axis ticks

### ISSUE THREAD

**Issue by doqhne** [NCAR/geocat-viz#73]
Right hand axis ticks/labels (raxis_ticks) are only used to set limits, not the actual ticks. For example, when raxis_ticks=np.arange(4, 29, 4) for conOncon_1, 4 is set as the lower bound for the y-limit, which is not right. Also, the heights 4, 8, 12... don't show up on the plot.
![rha_ticks](https://user-images.githubusercontent.com/99711690/178067088-12c0baf5-2ce4-4bca-95b0-f6b06bab4bd7.png)

**Comment by jukent** [comment]
Closing this because it is addressed by new height_from_pressure_axis function.
