### ISSUE TITLE
Adding Helper Function to Draw Curved Boundary Lines

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-viz#8]
References issue in geocat-examples: https://github.com/NCAR/GeoCAT-examples/issues/91
References these PRs in geocat-examples: https://github.com/NCAR/GeoCAT-examples/pull/73 and https://github.com/NCAR/GeoCAT-examples/pull/75

**Comment by erogluorhan** [comment]
@hCraker is the main text correct about https://github.com/NCAR/GeoCAT-examples/pull/75 would use this helper function?

**Comment by hCraker** [comment]
> @hCraker is the main text correct about [NCAR/GeoCAT-examples#75](https://github.com/NCAR/GeoCAT-examples/pull/75) would use this helper function?

Yes that is correct. You can draw circular boundaries using this function.

**Comment by erogluorhan** [comment]
> > @hCraker is the main text correct about [NCAR/GeoCAT-examples#75](https://github.com/NCAR/GeoCAT-examples/pull/75) would use this helper function?
> 
> Yes that is correct. You can draw circular boundaries using this function.

Thanks for the clarification!
