### ISSUE TITLE
Move Contour class to experimental branch for July release

### ISSUE THREAD

**Issue by anissa111** [NCAR/geocat-viz#82]

**Comment by erogluorhan** [comment]
Could you please clarify?

**Comment by anissa111** [comment]
> Could you please clarify?

Ahh yes, sorry! This was something discussed on zulip DMs. We talked about moving the contour class (and all the improvements Daphne made this summer) to an experimental branch of viz that will (hopefully? maybe?) have it's own, separate release.

@michaelavs @hCraker and I agree that some of the `Contour` features, while functional, are still very buggy and might not be something we want to ship out with all versions of geocat-viz. We've been finding a ton of bugs this summer as Daphne has been updating examples to use `Contour`. Heather is creating a similar branch in geocat-examples that will house all the examples that use `Contour` that will be visible on the version dropdown but not on the "latest" version.

**Comment by erogluorhan** [comment]
Oh, okay, thanks very much for the explanation!
