### ISSUE TITLE
AttributeError: module 'geocat.viz' has no attribute 'set_axes_limits_and_ticks'

### ISSUE THREAD

**Issue by Naveentk1992** [NCAR/geocat-viz#96]
While running the python program, program is about the basic scatter plot. But I am getting the error as 
"AttributeError: module 'geocat.viz' has no attribute 'set_axes_limits_and_ticks'". How can I overcome this issue?

**Comment by Naveentk1992** [comment]
Sorry for the late reply. I have an issue installing the geo cat-viz in my
workstation. I have followed the steps, but I still cannot do it. Could you
please give me some way or procedure for installing the geocat-viz.
*Thanks and Regards,*
Naveen T.K.,
Research Scholar,
Department of Energy Science and Engineering,
Indian Institute of Technology Delhi,
Hauz Khas, New Delhi, India -110016.

**Comment by jukent** [comment]
@Naveentk1992 What machine are you running on?

**Comment by Naveentk1992** [comment]
I am trying to install the geo cat-viz on Ubuntu 20.04.5 LTS with 64 GB
ram, 12th Gen Intel® Core™ i9-12900 × 24 processor.
*Thanks and Regards,*
Naveen T.K.,
Research Scholar,
Department of Energy Science and Engineering,
Indian Institute of Technology Delhi,
Hauz Khas, New Delhi, India -110016.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/02/23,
09:31:57 AM

**Comment by jukent** [comment]
I'll close this is in a week if we do not get more information. I hope this means you have solved your attribute error.
