### ISSUE TITLE
Unpin xarray from v2023.02.0

### ISSUE THREAD

**Issue by hCraker** [NCAR/geocat-viz#98]
Checks are [failing](https://github.com/NCAR/geocat-viz/actions/runs/4514227528/jobs/7950055457) due to a change in the latest version of xarray. Pinning xarray will solve the issue temporarily so we can release new changes to geocat-viz, but we will need to address the underlying cause at a later date.

**Comment by hCraker** [comment]
Xarray has been pinned in [PR #97](https://github.com/NCAR/geocat-viz/pull/97). This issue will remain opened until it is unpinned

**Comment by hCraker** [comment]
Xarray will be pinned in this PR https://github.com/NCAR/geocat-viz/pull/97

**Comment by kafitzgerald** [comment]
Noting that this is because of an issue in geocat-comp where it used internal API from xarray that recently changed: https://github.com/NCAR/geocat-comp/issues/381

**Comment by kafitzgerald** [comment]
Once xarray is (fully) pinned for comp in this upcoming release we should be able to remove our version pin here and just take care of things in comp instead of tracking elsewhere as well.

**Comment by kafitzgerald** [comment]
Blocked by: https://github.com/conda-forge/geocat-comp-feedstock/issues/31
